### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by thevikas** [skratchdot/react-bootstrap-daterangepicker#128]
(node_modules/react-bootstrap-daterangepicker/lib/index.js:94:19)

At Version: 3.2.2

**Comment by SidKwok** [comment]
@skratchdot I checked the commits and found that you have merge a pull-request to fix this warning. Will you release the new version?

**Comment by skratchdot** [comment]
@SidKwok - I just published `react-bootstrap-daterangepicker@3.3.0`.  See the changelog: https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/master/CHANGELOG.md

Thanks!

**Comment by giacomoguerci** [comment]
I still get the warning of this issue and of issue #126 despite having version 3.4.0 ( I didn't update from previous versions, I started using this package today).
I can provide more information if you need it.
